LANGUAGES = {
    'en': {
        'welcome': 'Welcome! I am a bot for selling XGramm (XGR) tokens.\nUse the buttons below to interact.',
        'buy': 'Buy',
        'balance': 'Balance',
        'profile': 'Profile',
        'language': 'Choose language',
        'cancel': 'Cancel',
        'back': 'Back',
        'choose_giver': 'Choose a giver:\n',
        'enter_address': 'You have chosen giver {giver_index}. Please enter your TON address.\n\nEnsure the address is correctly formatted and belongs to the TON network.',
        'confirm_purchase': 'To complete the purchase, please send the required amount of TON to the following address:\n\nAddress: {address}\nComment: {memo}\n\nAfter sending, confirm the transaction by clicking the button below.',
        'insufficient_data': 'Error: Insufficient data to confirm the purchase.',
        'cancel_purchase': 'Purchase canceled.',
        'send_payment': 'I sent TON',
        'cancel': 'Cancel',
        'checking_payment': 'Checking payment status...',
        'payment_received': 'Successfully sent {amount} XGR to address {address}',
        'payment_error': 'Error sending tokens',
        'check_again': 'Check again',
        'check_payment': 'Funds not received. Please check your transaction and try again.',
        'giver_balance': 'Giver {i}: {balance}/{total} XGR',
        'balance_info': 'Giver wallet balances:\n{balance_info}',
        'funds_not_received': 'Funds not received. Please check the transfer and try again.',
        'token_send_error': 'Error sending tokens',
        'user_not_found': 'Error: user not found in the database.',
        'tokens_purchased': 'Tokens purchased',
        'main_menu': 'Main Menu',
        'address_confirmed': 'Address confirmed. Please enter the amount of tokens to purchase.',
        'invalid_address': 'Invalid address entered. Please enter a correct TON address.',
        'complete_purchase': 'To complete the purchase, please send the required amount of TON to the following address:',
        'address': 'Address',
        'comment': 'Comment',
        'confirm_sent': 'I sent TON',
        'enter_valid_amount': 'Please enter a valid amount of tokens.',
        'use_start': 'Use /start to begin.',
        'confirm_operation': 'After sending, confirm the operation by clicking the button below.',
        'giver_balance': 'Giver {i}: {balance}/{total} XGR',
        'choose_giver': 'Choose a giver:\n',
        'balance_info': 'Balance of givers\' wallets:\n{balance_info}',
        'successful_transfer': 'Successfully sent {token_amount} XGR to the address {user_address}'
    },
    'ru': {
        'welcome': 'Привет! Я бот для продажи XGramm (XGR) токенов.\nИспользуйте кнопки ниже для взаимодействия.',
        'buy': 'Купить',
        'balance': 'Баланс',
        'profile': 'Профиль',
        'language': 'Выбрать язык',
        'back': 'Назад',
        'cancel': 'Отмена',
        'choose_giver': 'Выберите гивера:\n',
        'enter_address': 'Вы выбрали гивера {giver_index}. Пожалуйста, введите ваш адрес TON.\n\nУбедитесь, что адрес указан без лишних знаков и пробелов, и принадлежит сети TON.',
        'confirm_purchase': 'Для завершения покупки, пожалуйста, отправьте необходимую сумму TON на следующий адрес:\n\nАдрес: {address}\nКомментарий: {memo}\n\nПосле отправки, подтвердите операцию, нажав кнопку ниже.',
        'insufficient_data': 'Ошибка: Недостаточно данных для подтверждения покупки.',
        'cancel_purchase': 'Покупка отменена.',
        'send_payment': 'Я отправил TON',
        'cancel': 'Отменить',
        'checking_payment': 'Проверка статуса платежа...',
        'payment_received': 'Успешно отправлено {amount} XGR на адрес {address}',
        'payment_error': 'Ошибка при отправке токенов',
        'check_again': 'Проверить снова',
        'check_payment': 'Средства не поступили. Пожалуйста, проверьте отправку и попробуйте снова.',
        'giver_balance': 'Гивер {i}: {balance} XGR',
        'balance_info': 'Баланс кошельков гиверов:\n{balance_info}',
        'successful_transfer': 'Успешно отправлено {token_amount} XGR на адрес {user_address}',
        'token_send_error': 'Ошибка при отправке токенов',
        'user_not_found': 'Ошибка: пользователь не найден в базе данных.',
        'tokens_purchased': 'Количество купленных токенов',
        'main_menu': 'Главное меню',
        'address_confirmed': 'Адрес подтвержден. Пожалуйста, введите количество токенов для покупки.',
        'invalid_address': 'Введен некорректный адрес. Пожалуйста, введите правильный адрес TON.',
        'complete_purchase': 'Для завершения покупки, пожалуйста, отправьте необходимую сумму TON на следующий адрес:',
        'address': 'Адрес',
        'comment': 'Комментарий',
        'confirm_operation': 'После отправки, подтвердите операцию, нажав кнопку ниже.',
        'confirm_sent': 'Я отправил TON',
        'enter_valid_amount': 'Пожалуйста, введите корректное количество токенов.',
        'use_start': 'Используйте /start для начала.',
        'giver_balance': 'Гивер {i}: {balance}/{total} XGR',
        'choose_giver': 'Выберите гивера:\n',
        'balance_info': 'Баланс кошельков гиверов:\n{balance_info}',
        'funds_not_received': 'Средства не поступили. Пожалуйста, проверьте отправку и попробуйте снова.'
    },
    'uk': {
        'welcome': 'Вітаю! Я бот для продажу токенів XGramm (XGR).\nВикористовуйте кнопки нижче для взаємодії.',
        'buy': 'Купити',
        'balance': 'Баланс',
        'profile': 'Профіль',
        'language': 'Обрати мову',
        'back': 'Назад',
        'cancel': 'Скасувати',
        'choose_giver': 'Виберіть гівера:\n',
        'enter_address': 'Ви вибрали гівера {giver_index}. Будь ласка, введіть вашу адресу TON.\n\nПереконайтеся, що адресу вказано без зайвих знаків і пробілів, і належить мережі TON.',
        'confirm_purchase': 'Для завершення покупки, будь ласка, відправте необхідну суму TON на наступну адресу:\n\nАдреса: {address}\nКоментар: {memo}\n\nПісля відправки підтвердіть операцію, натиснувши кнопку нижче.',
        'insufficient_data': 'Помилка: Недостатньо даних для підтвердження покупки.',
        'cancel_purchase': 'Покупку скасовано.',
        'send_payment': 'Я відправив TON',
        'cancel': 'Скасувати',
        'checking_payment': 'Перевірка статусу платежу...',
        'payment_received': 'Успішно відправлено {amount} XGR на адресу {address}',
        'payment_error': 'Помилка при відправці токенів',
        'check_again': 'Перевірити знову',
        'check_payment': 'Кошти не надійшли. Будь ласка, перевірте вашу транзакцію і спробуйте ще раз.',
        'giver_balance': 'Гивер {i}: {balance}/{total} XGR',
        'balance_info': 'Баланс гаманців гіверів:\n{balance_info}',
        'successful_transfer': 'Успішно відправлено {token_amount} XGR на адресу {user_address}',
        'token_send_error': 'Помилка при відправленні токенів',
        'user_not_found': 'Помилка: користувача не знайдено в базі даних.',
        'tokens_purchased': 'Кількість куплених токенів',
        'main_menu': 'Головне меню',
        'address_confirmed': 'Адресу підтверджено. Будь ласка, введіть кількість токенів для покупки.',
        'invalid_address': 'Введено некоректну адресу. Будь ласка, введіть правильну адресу TON.',
        'complete_purchase': 'Для завершення покупки, будь ласка, надішліть необхідну суму TON на наступну адресу:',
        'address': 'Адреса',
        'comment': 'Коментар',
        'confirm_operation': 'Після відправки підтвердьте операцію, натиснувши кнопку нижче.',
        'confirm_sent': 'Я відправив TON',
        'enter_valid_amount': 'Будь ласка, введіть правильну кількість токенів.',
        'use_start': 'Використовуйте /start для початку.',
        'giver_balance': 'Гівер {i}: {balance}/{total_balance} XGR',
        'choose_giver': 'Виберіть гівера:\n',
        'balance_info': 'Баланс гаманців гіверів:\n{balance_info}',
        'funds_not_received': 'Кошти не надійшли. Будь ласка, перевірте відправку та спробуйте знову.'
    }
}
